# Standards: 1.2
---
apt_unattended_upgrade_remove_unused_deps: True
apt_unattended_upgrade_remove_unused_kernel: True

apt_periodic_config:
  - name: Update-Package-Lists
    value: 1
  - name: Download-Upgradeable-Packages
    value: 1
  - name: AutocleanInterval
    value: 7
  - name: Unattended-Upgrade
    value: 1

apt_redundant_configs:
  - 20auto-upgrades
  - 99apt-dater-host_periodic

...
