# Standards: 1.2
---
root_password: "{{ lookup('file', 'secrets/chnum/root_password.txt') | password_hash('sha512', lookup('file', 'secrets/chnum/root_salt.txt')) }}"

root_sshkeys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINaQYR0/Oj6k1H03kshz2J7rlGCaDSuaGPhhOs9FcZfn thomas@osiris

root_shell: /bin/zsh
root_ohmyzsh: True

root_castles_force: True
root_castles:
  - tboerger/homeshick-base
  - tboerger/homeshick-linux

...
